---
- name: redhat | Installing Pre-Reqs
  yum:
    name: ["iproute", "sudo", "which"]
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: set url on frr version less than or equal to 4.1
  set_fact:
    frr_url_part: "{{ frr_release_date }}"
  when:
    - frr_version <= "4.1"

- name: set url on frr version 5
  set_fact:
    frr_url_part: "001"
  when:
    - frr_version == "5.0.2"

- name: set url on frr version 6
  set_fact:
    frr_url_part: "01"
  when:
    - frr_version >= "6"

- name: redhat | Create FRR {{ frr_version }} install
  set_fact:
    frr_debs:
      [
        "{{ frr_package_url }}/frr-{{ frr_version }}-{{ frr_url_part }}.el7.centos.x86_64.rpm",
      ]
  become: true
  when:
    - ansible_distribution_major_version != "8"

- name: redhat | Create Python Tools FRR {{ frr_version }} install
  set_fact:
    frr_package_deb: "{{ frr_package_url }}/frr-pythontools-{{ frr_version }}-{{ frr_url_part }}.el7.centos.x86_64.rpm"
  when:
    - ansible_distribution_major_version != "8"

- name: redhat | Combine FRR {{ frr_version }} and tools
  set_fact:
    frr_debs: "{{ frr_debs }} + [ '{{ frr_package_deb }}' ]"
  when: 
    - frr_reload|bool
    - ansible_distribution_major_version != "8"

- name: redhat | Installing FRR {{ frr_version }}
  yum:
    name: "{{ frr_debs }}"
    state: present
  become: true
  register: _frrdownload
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: redhat | Installing FRR Vendor Package
  dnf:
    name: "frr"
    state: present
  become: true
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_major_version == "8"
